#!/usr/bin/env bash
# set -e
set -u
set -x

./pacman-add
./groups-add
./udev-add

yes |sudo pacman -S unixodbc zoxide direnv

# Build essentials, to be installed before everything,
# including Rust.

yes |sudo pacman -S chezmoi yay micro nix doctest cmake meson
yes |sudo pacman -S fakeroot base-devel clang doxygen rustup catch2 gtest trompeloeil
rustup toolchain install stable

if [ ! -d ~/.zshrc.old ]; then
  cp ~/.zshrc ~/.zshrc.old
fi

# Ecosystem essentials.

../noto-nerd-install

echo "!!! REBOOT !!!"
sudo shutdown -r now
