#!/usr/bin/env bash
# set -e
set -u
set -x

./rust-install
./base-install
./extras-install
# ./flutter-install
./spell-install
./nvim-install
# ./doom-install
./nix-init
./racket-install
./typst-install
chezmoi apply -v
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install  # Say no to Do you want to update your shell config...
