#!/usr/bin/env bash
# set -e
set -u
set -x

# Build essentials, to be installed before everything,
# including Rust.

#./pacman-add  # pacman-add can be run just once!

sudo pacman -S chezmoi yay micro nix doctest cmake meson
sudo pacman -S fakeroot base-devel clang doxygen rustup catch2 gtest trompeloeil
rustup toolchain install stable

if [ ! -d ~/.zshrc.old ]; then
  cp ~/.zshrc ~/.zshrc.old
fi

# Ecosystem essentials.

../noto-nerd-install
#./admin-add
