#!/usr/bin/env bash
# set -e
set -u
set -x

# ./rwasm-install
./base-install
./extras-install
# ./flutter-install  # Not yet ready without AUR.
./spell-install
./nvim-install
# ./doom-install  # Probably outdated.
./qemu-install
# ./nix-init
# ./racket-install
./typst-install
chezmoi apply --force
gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#FFD700'
