#!/usr/bin/env bash
# set -e
set -u
set -x

# ./rwasm-install
./base-install
./extras-install
./spell-install
./nvim-install
# ./doom-install  # Probably outdated.
# ./qemu-install
# ./nix-init
# ./racket-install
./typst-install
chezmoi apply --force
if [[ "$XDG_CURRENT_DESKTOP" == "GNOME" ]]; then
  gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#FFD700'
  gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
  gsettings set org.gnome.desktop.media-handling automount false
  gsettings set org.gnome.desktop.media-handling automount-open false
  gsettings set org.gtk.Settings.FileChooser sort-directories-first true
  gsettings set org.gtk.Settings.FileChooser show-hidden true
fi
