#!/usr/bin/env bash
# set -e
set -u
set -x

yay -S docker
yay -S docker-compose
yay -S docker-buildx
docker buildx install
sudo systemctl enable docker

yay -S zsh-nix-shell
yay -S nix-zsh-completions

yay -S partitionmanager
yay -S fastfetch  # System info.
yay -S kdialog
yay -S direnv
yay -S oh-my-zsh-git
yay -S python-virtualenvwrapper
yay -S python-pipx
yay -S mlocate
yay -S xorg-xinput
yay -S lazygit
yay -S tig
yay -S tmux
yay -S debtap  # Install deb packages.
# yay -S shellcheck-bin
yay -S atool  # Universal archive manager.
yay -S ouch
yay -S unzip

yay -S tk  # Crossplatform widget toolkit.
yay -S unixodbc
yay -S wxwidgets-common
yay -S wxwidgets-gtk3

yay -S zoxide
yay -S ripgrep
yay -S fd
yay -S sd
yay -S bat
yay -S exa
yay -S tree
yay -S erdtree
yay -S htop
yay -S btop
yay -S bottom
yay -S dust
yay -S procs
yay -S tealdeer
# yay -S broot
yay -S skim  # Fuzzy Finder in Rust.
yay -S tokei
yay -S difftastic
yay -S dos2unix

yay -S mpv
# yay -S youtube-dl
yay -S yt-dlp-drop-in
yay -S yt-dlp
yay -S ffmpeg
yay -S rtmpdump
yay -S atomicparsley
yay -S aria2
yay -S python-mutagen
yay -S python-pycryptodomex
yay -S python-websockets

yay -S rpi-imager
yay -S gnome-disk-utility
yay -S gdu

yay -S ttf-liberation
yay -S ttf-dejavu

yay -S fontforge
yay -S noto-fonts
yay -S noto-fonts-emoji
yay -S noto-color-emoji-fontconfig
yay -S alacritty
yay -S alacritty-themes

# Sway

yay -S network-manager-applet
yay -S waybar
yay -S sway

# Clipboard.

yay -S xsel
yay -S xclip
yay -S wl-clipboard

# Virtual Keyboard.

yay -S xdotool
yay -S wtype

# Viewers.

yay -S zathura
yay -S zathura-pdf-poppler

# i3.

yay -S i3-wm
yay -S i3status
yay -S dmenu-manjaro
yay -S i3lock
yay -S feh

# IBus.

yay -S ibus
yay -S ibus-m17n

# CUPS drivers for SPL (Samsung Printer Language) printers.

yay -S splix

# Python, forgettable.

pipx install poetry
yay -S python-lsp-server
yay -S python-black
yay -S ipython
yay -S ptpython

yay -S bash-language-server
yay -S bash-completion
yay -S lua-language-server
yay -S taplo  # TOML toolkit.
yay -S yaml-language-server

# C++, forgettable.

yay -S doctest catch2 gtest trompeloeil
yay -S meson

# JS, forgettable.

yay -S npm
# npm install --global state-machine-cat

# Ruby, forgettable.

# yay -S fpm  # Build packages: deb, rpm, etc.

# Perl, forgettable.

# yay -S perl-yaml-tiny
# yay -S perl-file-homedir
