#!/usr/bin/env bash
# set -e
set -u
set -x

yes | sudo pacman -S mise
mise trust ~

rustup component add rust-analyzer
yes | sudo pacman -S cargo-binstall cargo-update

yes | sudo pacman -S docker docker-compose docker-buildx

docker buildx install
sudo systemctl enable --now docker

#sudo pacman -S kdialog

yes | sudo pacman -S ttf-liberation ttf-dejavu fontforge alacritty taglib1

yes | sudo pacman -S partitionmanager fastfetch python-pipx mlocate sdkmanager
yes | sudo pacman -S gparted grsync lazygit tig tmux atool ouch

yes | sudo pacman -S tk wxwidgets-common wxwidgets-gtk3

yes | sudo pacman -S ripgrep fd sd bat exa tree erdtree htop btop bottom dust procs tealdeer
yes | sudo pacman -S skim tokei difftastic dos2unix dysk caligula pastel astroterm

yes | sudo pacman -S mpv yt-dlp ffmpeg rtmpdump atomicparsley aria2 python-mutagen
yes | sudo pacman -S python-pycryptodomex python-websockets

yes | sudo pacman -S rpi-imager gnome-disk-utility smartmontools gdu
yes | sudo pacman -S platformio-core platformio-core-udev

# Java.

yes | sudo pacman -S java-runtime-common jdk21-openjdk

# Network.

yes | sudo pacman -S traceroute mtr nmap

# Clipboard.

yes | sudo pacman -S xsel xclip wl-clipboard

# Virtual Keyboard.

yes | sudo pacman -S xdotool wtype

# Viewers.

yes | sudo pacman -S zathura zathura-pdf-poppler

# i3.

#yes | sudo pacman -S i3-wm i3status dmenu i3lock feh

# IBus.

yes | sudo pacman -S ibus

# CUPS drivers for SPL (Samsung Printer Language) printers.

yes | sudo pacman -S splix

# Python, forgettable.

pipx install poetry
pipx install uv
pipx install mkdocs-material --include-deps

yes | sudo pacman -S python-lsp-server python-black ipython ptpython
yes | sudo pacman -S bash-language-server bash-completion lua-language-server yaml-language-server
