#!/usr/bin/env bash
# set -e
set -u
set -x

sudo pacman -S yay
yay -S fakeroot

yay -S base-devel
yay -S docker
yay -S docker-compose
yay -S docker-buildx
docker buildx install

yay -S oh-my-zsh-git
yay -S python-virtualenvwrapper
yay -S python-pipx
yay -S mlocate
yay -S atool
yay -S lazygit
yay -S tig
yay -S tmux
yay -S debtap
yay -S shellcheck-bin

yay -S zoxide
yay -S ripgrep
yay -S fd
yay -S sd
yay -S bat
yay -S exa
yay -S tree
yay -S erdtree
yay -S htop
yay -S btop
yay -S bottom
yay -S dust
yay -S procs
yay -S tealdeer
# yay -S broot
yay -S skim
yay -S tokei
yay -S ouch
yay -S difftastic

yay -S mpv
# yay -S youtube-dl
yay -S yt-dlp-drop-in
yay -S yt-dlp
yay -S ffmpeg
yay -S rtmpdump
yay -S atomicparsley
yay -S aria2
yay -S python-mutagen
yay -S python-pycryptodomex
yay -S python-websockets

yay -S rpi-imager
yay -S gnome-disk-utility
yay -S gdu

yay -S ttf-liberation
yay -S ttf-dejavu

yay -S fontforge
yay -S noto-fonts
yay -S noto-fonts-emoji
yay -S noto-color-emoji-fontconfig
yay -S alacritty
yay -S alacritty-themes

# Clipboard.

yay -S xsel
yay -S xclip
yay -S wl-clipboard

# i3.

yay -S i3-wm
yay -S i3status
yay -S dmenu-manjaro
yay -S i3lock
yay -S feh

# IBus.

yay -S ibus
yay -S ibus-m17n

# CUPS drivers for SPL (Samsung Printer Language) printers.

yay -S splix

# Python, forgettable.

pipx install poetry
yay -S python-lsp-server
yay -S python-black

# C++, forgettable.

yay -S doctest catch2 gtest

# JS, forgettable.

yay -S npm
npm install --global state-machine-cat

# Ruby, forgettable.

yay -S fpm
