#!/usr/bin/env bash
# set -e
set -u
set -x

# Doom Emacs.
yes |sudo pacman -S pyright texlab
rm -rf ~/.emacs.d
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
yes |sudo pacman -S emacs-nativecomp
doom install
