#!/usr/bin/env bash
# set -e
set -u
set -x

# asdf, Erlang, and Elixir.

yay -S asdf-vm
yay -S fop
# yay -S kerl
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
cd ~  # .tool-versions expected there.
asdf install
