#!/usr/bin/env bash
# set -e
set -u
set -x

# asdf, Erlang, and Elixir.

yay -S fop

git clone https://github.com/asdf-vm/asdf.git ~/.asdf
asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git
cd ~  # .tool-versions expected there.
export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"
asdf install
