#!/usr/bin/env bash
# set -e
set -u
set -x

# Miscellaneous applications.

# yay -S google-chrome
# yay -S qutebrowser  # Good but heavy.
yay -S geany geany-plugins
yay -S retext
if [ $(uname -m) == 'x86_64' ]; then
#     yay -S doublecmd-qt5
#     yay -S fontmatrix  # Not recommended before adding archlinuxcn repo (due to qt5-webkit dependency).
#     yay -S foxitreader  # Not recommended before adding andontie-aur repo.
    yay -S ghcup-hs-bin  # Haskell, starting the right way.
    yay -S pandoc-bin
#     yay -S arduino-ide-bin  # Not recommended before adding archlinuxcn repo.
#     yay -Ss stm32cubeprog  # Installation script may hang.
#     yay -S deadbeef opusfile
    yay -S qmmp
#     yay -S pulseview-git
    yay -S zoom
#     yay -S yacreader
#     yay -S esplorer
#     yay -S anki-official-binary-bundle
#     yay -S rstudio-desktop-bin
fi
