#!/usr/bin/env bash
# set -e
set -u
set -x

# Miscellaneous applications.

sudo pacman -S dolphin okular gwenview
yes | sudo pacman -S dolphin-plugins ffmpegthumbs kdegraphics-thumbnailers

yes | sudo pacman -S thunar tumbler android-file-transfer # android-udev ?
yes | sudo pacman -S catfish thunar-volman thunar-archive-plugin thunar-media-tags-plugin

#./m17n-add

#yes | sudo pacman -S pulseview-qt6-git
#yes | yay -S watchman-bin

#yes | sudo pacman -S qutebrowser
#yes | sudo pacman -S tor-browser-bin
#yes | sudo pacman -S google-chrome
#yes | sudo pacman -S telegram-desktop
#yes | sudo pacman -S warpinator

#yes | sudo pacman -S obs-studio
#yes | sudo pacman -S qmmp
#yes | sudo pacman -S deadbeef opusfile

#yes | sudo pacman -S vscodium
#yes | sudo pacman -S arduino-ide arduino-language-server
#yes | sudo pacman -S zoom
#yes | sudo pacman -S kicad kicad-library kicad-library-3d python-kikit

#cargo install --locked --git https://github.com/Decodetalkers/flutterup
#flutterup install

if [[ "$XDG_CURRENT_DESKTOP" == "GNOME" ]]; then
  ../kde-to-gnome
  yes | sudo pacman -S gnome-shell-extension-dash-to-dock
  yes | sudo pacman -S dconf-editor
  #yes | sudo pacman -S gthumb # gwenview alternative
fi

yes | sudo pacman -S vlc vlc-plugins-all
yes | sudo pacman -S geany geany-plugins retext foliate arianna qbittorrent
yes | sudo pacman -S scrcpy vorbis-tools pandoc-bin
yes | sudo pacman -S libusb-compat python-pyserial
yes | sudo pacman -S evince papers
yes | sudo pacman -S yacreader

yes | cargo binstall tex-fmt

#     yay -S kwin-scripts-krohnkite
#     yay -S doublecmd-qt5
#     yay -S fontmatrix  # Not recommended before adding archlinuxcn repo (due to qt5-webkit dependency).
#     yay -S foxitreader  # Not recommended before adding andontie-aur repo.
#     yay -S ml4w-hyprland-git ml4w-hyprland-setup
#     yay -S jetbrains-toolbox  # The right way for getting free PyCharm Community and Android Studio.
#     yay -S juliaup-bin
#     yay -S ghcup-hs-bin  # Haskell, starting the right way (ghcup tui).
#     yay -S fop  # Erlang/Elixir obscure dependency, requires a lot of Java!
#     yay -S texlive-dummy
#     yay -S modpoll-bin  # Modbus master CLI simulator.
#     yay -S qmodbus-git  # Modbus master GUI simulator.
#     yay -Ss stm32cubeprog  # Installation script may hang.
#     yay -S puddletag  # An audio tag editor.
#     yay -S kdenlive  # Video editor.
#     yay -S ocenaudio-bin  # Audio editor.
#     yay -S snd  # Audio editor.
#     yay -S esplorer
#     yay -S anki-official-binary-bundle
#     yay -S rstudio-desktop-bin
