#!/usr/bin/env bash
# set -e
set -u
set -x

sudo gpasswd -a $USER uucp
sudo gpasswd -a $USER nix-users

sudo groupadd docker
sudo gpasswd -a $USER docker

sudo groupadd libvirt
sudo usermod -aG libvirt $USER

sudo groupadd kvm
sudo usermod -aG kvm $USER
