#!/usr/bin/env bash
# set -e
set -u
set -x

# MicroPython.

pipx install adafruit-ampy
pipx install rshell

# AstroNvim.
#
# NB Before starting nvim for the first time, make sure that npm is available.

#yay -S neovim-remote  # (AUR only).
yes |sudo pacman -S npm
yes |sudo pacman -S python-pynvim tree-sitter python-jedi neovide

sudo rm -rf ~/.cache/nvim ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim

git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
sudo rm -rf ~/.config/nvim/.git
yes |sudo pacman -S neovim

chezmoi apply --force

