#!/usr/bin/env bash
# set -e
set -u
set -x

# MicroPython.

yay -S adafruit-ampy  # (AUR only).
yay -S rshell  # (AUR only).

# AstroNvim.

yay -S python-pynvim
yay -S neovim-remote  # (AUR only).
yay -S tree-sitter
# yay -S tree-sitter-python-git  # Orphaned and aren't crossplatform anyway.
# yay -S tree-sitter-rust-git
yay -S python-jedi
yay -S python-pylint
yay -S neovide
git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
yay -S neovim
