#!/usr/bin/env bash
# set -e
set -u
set -x

# The script also serves the clean reinstall,
# can be run securely multiple times.

# MicroPython.

uv tool install adafruit-ampy
uv tool install rshell
uv tool install mpremote

# AstroNvim.
#
# NB Before starting nvim for the first time, make sure that npm is available.

#yay -S neovim-remote  # (AUR only).

if [ ! "$(command -v npm)" ]; then
    yes | sudo pacman -S npm
fi

yes | sudo pacman -S python-pynvim tree-sitter python-jedi neovide luarocks

sudo rm -rf ~/.cache/nvim ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim

git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
sudo rm -rf ~/.config/nvim/.git
yes | sudo pacman -S neovim

chezmoi apply --force
