#!/usr/bin/env bash
# set -e
set -u
set -x

# This script adds unofficial repositories to /etc/pacman.conf
# It can be run securely multiple times.

# Use tee: https://stackoverflow.com/questions/84882/sudo-echo-something-etc-privilegedfile-doesnt-work
# Use multiline: https://unix.stackexchange.com/questions/678930/how-do-you-output-a-multi-line-string-that-includes-slashes-and-other-special-ch

sudo pacman -Sy archlinux-keyring && sudo pacman -Syyu

if ! grep -q appendiX /etc/pacman.conf; then
printf '\n\n# Custom appendiX to the end of file

[options]
Color

IgnorePkg   = ibus-m17n

[archlinuxcn]
Server = http://repo.archlinuxcn.org/$arch
## or install archlinuxcn-mirrorlist-git and use the mirrorlist
#Include = /etc/pacman.d/archlinuxcn-mirrorlist

[andontie-aur]
Server = https://aur.andontie.net/$arch

[wee-green-arch-repo]
SigLevel = Optional TrustAll
Server = https://tyrn.github.io/$repo/$arch
#Server = file:///home/alexey/arch-repos/$repo/$arch

[ownstuff]
#Server = https://ftp.f3l.de/~martchus/$repo/os/$arch
Server = https://martchus.dyn.f3l.de/repo/arch/$repo/os/$arch' | sudo tee -a /etc/pacman.conf
fi

# Required by archlinuxcn
sudo pacman-key --lsign-key "farseerfc@archlinux.org"
# Required by andontie-aur
sudo pacman-key --recv-key 72BF227DD76AE5BF
sudo pacman-key --lsign-key 72BF227DD76AE5BF
# Required by ownstuff
sudo pacman-key --recv-key B9E36A7275FC61B464B67907E06FE8F53CDC6A4C
sudo pacman-key --lsign-key B9E36A7275FC61B464B67907E06FE8F53CDC6A4C

sudo pacman -Syy
sudo pacman -S archlinuxcn-keyring 
