#!/usr/bin/env bash
# set -e
set -u
set -x

# QEMU/KVM/Virtual Machine Manager.
# Necessary groups already set by groups-add.

yes |sudo pacman -S qemu-full virt-manager

sudo systemctl enable --now libvirtd
