#!/usr/bin/env bash
# set -e
set -u
set -x

# Rust.

sudo pacman -S yay
yay -S fakeroot

yay -S base-devel
yay -S clang
yay -S doxygen

yay -S rustup
rustup toolchain install nightly
rustup component add rust-analyzer
# rustup component add rust-src
cargo install cargo-binstall

# Updating cargo-binstall: cargo binstall cargo-binstall
