#!/usr/bin/env bash
# set -e
set -u
set -x

rm -rf ~/.oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

chezmoi apply --force

#git clone --depth 1 https://github.com/zsh-users/zsh-256color "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-256color
git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
