#!/usr/bin/env bash
# set -e
set -u
set -x

sudo pacman -S yay
yay -S fakeroot

yay -S base-devel
yay -S docker
yay -S docker-compose
yay -S docker-buildx
docker buildx install

yay -S oh-my-zsh-git
yay -S python-virtualenvwrapper
yay -S python-pipx
yay -S mlocate
yay -S lazygit
yay -S tmux
yay -S shellcheck-bin

yay -S zoxide
yay -S ripgrep
yay -S fd
yay -S sd
yay -S bat
yay -S exa
yay -S dust
yay -S procs
yay -S tealdeer
yay -S broot
yay -S skim
yay -S tokei
yay -S ouch
yay -S difftastic

yay -S rpi-imager
yay -S gnome-disk-utility

yay -S ttf-liberation
yay -S ttf-dejavu

yay -S noto-fonts
yay -S noto-fonts-emoji
yay -S noto-color-emoji-fontconfig
yay -S alacritty
yay -S alacritty-themes

# i3.

yay -S i3-wm
yay -S i3status
yay -S dmenu-manjaro
yay -S i3lock
yay -S feh

# IBus.

yay -S ibus
yay -S ibus-m17n

# CUPS drivers for SPL (Samsung Printer Language) printers.

yay -S splix

# Neovim.

yay -S npm
npm install --global state-machine-cat

yay -S python-pynvim
yay -S neovim-remote
yay -S tree-sitter
yay -S tree-sitter-python-git
yay -S tree-sitter-rust-git
yay -S python-jedi
yay -S python-pylint
yay -S xsel
yay -S xclip
yay -S aspell
yay -S aspell-en
yay -S aspell-es
yay -S aspell-ru
yay -S neovim

# Doom Emacs.

yay -S python-lsp-server
yay -S pyright
yay -S rust-analyzer
yay -S texlab
yay -S hunspell
yay -S hunspell-en_us
yay -S hunspell-es_es
yay -S hunspell-ru
rm -rf ~/.emacs.d
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
yay -S emacs-nativecomp
doom install
