#!/usr/bin/env bash
# set -e
set -u
set -x

sudo pacman -S yay
yay -S fakeroot

yay -S base-devel
yay -S docker
yay -S docker-compose
yay -S docker-buildx
docker buildx install

yay -S oh-my-zsh-git
yay -S python-virtualenvwrapper
yay -S mlocate
yay -S lazygit
yay -S tmux
yay -S zoxide
yay -S ripgrep
yay -S bat

yay -S rpi-imager

yay -S ttf-liberation
yay -S ttf-dejavu

yay -S noto-fonts
yay -S noto-fonts-emoji
yay -S noto-color-emoji-fontconfig
yay -S alacritty
yay -S alacritty-themes

# i3.

yay -S i3-wm
yay -S i3status
yay -S dmenu-manjaro
yay -S i3lock

# IBus.

yay -S ibus
yay -S ibus-m17n

# Neovim.

yay -S python-pynvim
yay -S neovim-remote
yay -S tree-sitter
yay -S tree-sitter-python-git
yay -S tree-sitter-rust-git
yay -S python-jedi
yay -S python-pylint
yay -S npm
yay -S xsel
yay -S aspell
yay -S neovim

# Doom Emacs.

yay -S python-lsp-server
yay -S pyright
yay -S rust-analyzer
yay -S texlab
yay -S hunspell
yay -S hunspell-en_us
yay -S hunspell-es_es
yay -S hunspell-ru
rm -rf ~/.emacs.d
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
yay -S emacs-nativecomp
doom install
