#!/usr/bin/env bash
# set -e
set -u
set -x

# CHECK /etc/environment VISUALLY FIRST!

# This script adds variables to /etc/environment
# It can be run securely multiple times.

# Use tee: https://stackoverflow.com/questions/84882/sudo-echo-something-etc-privilegedfile-doesnt-work
# Use multiline: https://unix.stackexchange.com/questions/678930/how-do-you-output-a-multi-line-string-that-includes-slashes-and-other-special-ch

if ! grep -q appendiX /etc/environment; then
  # shellcheck disable=SC2016
  printf '\n# Custom appendiX to the end of file
QT_QPA_PLATFORMTHEME=qt6ct\n' | sudo tee -a /etc/environment
fi
