#!/usr/bin/env bash

echo "Creating fonts folder: ${HOME}/.fonts"
mkdir -p  "$HOME/.fonts"

# A behemoth: Noto Nerd fonts.

nerd_name="Noto"
nerd_file="$nerd_name.zip"
nerd_url="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$nerd_file"

nerd_download_dir="$HOME/Downloads/Fonts/$nerd_name"
mkdir -p "$nerd_download_dir"

echo "Starting download $nerd_name nerd font"

cd "$nerd_download_dir"

if ! test -e "$nerd_file"; then
    if [ "$(command -v curl)" ]; then
        echo "$nerd_url"
        curl -OL "$nerd_url"
    elif [ "$(command -v wget)" ]; then
        echo "$nerd_url"
        wget "$nerd_url"
    else
        echo "Fatal error: no curl, no wget on the system"
        exit 1
    fi
fi

echo "unzip the $nerd_file"
unzip "$nerd_file" -d "$HOME/.fonts/$nerd_name/"

# A tiny addition: the Church Slavonic fonts.

slav_name="fonts-churchslavonic"
slav_file="$slav_name.zip"
slav_url="https://www.ponomar.net/files/$slav_file"

slav_download_dir="$HOME/Downloads/Fonts/$slav_name"
mkdir -p "$slav_download_dir"

echo "Starting download $slav_name nerd font"

cd "$slav_download_dir"

if ! test -e "$slav_file"; then
    if [ "$(command -v curl)" ]; then
        echo "$slav_url"
        curl -OL "$slav_url"
    elif [ "$(command -v wget)" ]; then
        echo "$slav_url"
        wget "$slav_url"
    else
        echo "Fatal error: no curl, no wget on the system"
        exit 1
    fi
fi

echo "unzip the $slav_file"
unzip "$slav_file" -d "$HOME/.fonts/$slav_name/"

fc-cache -fv
echo "Done!"
