#!/usr/bin/env bash

fonts_unzip_to="$HOME/.fonts"
downloads_fonts="$HOME/Downloads/Fonts"

function font_install_zip() {
    local font_name=$1
    local font_file="$font_name.zip"
    local deeper=$2
    local font_folder=$3
    local font_url="$font_folder/$font_file"
    local font_download_dir="$downloads_fonts$deeper/$font_name"

    mkdir -p "$font_download_dir"
    echo "Starting download $font_name font"
    cd "$font_download_dir" || exit 1

    if ! test -e "$font_file"; then
        if [ "$(command -v curl)" ]; then
            echo "$font_url"
            curl -OL "$font_url"
        elif [ "$(command -v wget)" ]; then
            echo "$font_url"
            wget "$font_url"
        else
            echo "Fatal error: no curl, no wget on the system"
            exit 1
        fi
    fi

    echo "unzip the $font_file"
    mkdir -p "$fonts_unzip_to$deeper"
    unzip "$font_file" -d "$fonts_unzip_to$deeper/$font_name/"
}

if [ $# -eq 0 ]; then

    # A behemoth: Noto Nerd fonts.

    font_install_zip \
        "Noto" \
        "" \
        "https://github.com/ryanoasis/nerd-fonts/releases/latest/download"

    # A tiny addition: the Church Slavonic fonts.

    font_install_zip \
        "fonts-churchslavonic" \
        "" \
        "https://www.ponomar.net/files"

else # Church Slavonic legacy only.

    font_install_zip \
        "fonts-churchslavonic" \
        "/legacy" \
        "https://github.com/typiconman/fonts-cu/releases/download/v2.2.1"

fi

fc-cache -fv
echo "Done!"
