#!/usr/bin/env bash
# set -e
set -u
set -x

# The script can be run securely multiple times.

rm -rf ~/.fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
yes | ~/.fzf/install

chezmoi apply --force
