#!/usr/bin/env bash
# set -e
set -u
set -x

# This script is safe to run multiple times

temp_dir=$(mktemp -d)

cleanup() {
	rm -rf "$temp_dir"
	echo "Cleaned up: $temp_dir"
}

# Register cleanup for various exit signals
trap cleanup EXIT INT TERM

# Unsafe Mode button to GNOME Main Menu
# (not required for switch-keyboard-layout)

cd "$temp_dir" || exit
git clone https://github.com/linushdot/unsafe-mode-menu.git
cd unsafe-mode-menu || exit
mkdir -p ~/.local/share/gnome-shell/extensions/
rm -rf ~/.local/share/gnome-shell/extensions/unsafe-mode-menu@linushdot.local
cp -r unsafe-mode-menu@linushdot.local ~/.local/share/gnome-shell/extensions/
