#!/usr/bin/env bash
# set -e
set -u
set -x

if [ ! "$(command -v gsettings)" ]; then
  echo "No gsettings utility found"
  exit 1
fi

if [ ! $# -eq 0 ]; then
  # Some argument passed; show a selection of settings
  gsettings get org.gtk.Settings.FileChooser sort-directories-first
  gsettings get org.gtk.gtk4.Settings.FileChooser sort-directories-first
  exit 0
fi

gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#FFD700'
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
gsettings set org.gnome.desktop.media-handling automount false
gsettings set org.gnome.desktop.media-handling automount-open false
gsettings set org.gtk.Settings.FileChooser sort-directories-first true
gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true
gsettings set org.gtk.Settings.FileChooser show-hidden true
gsettings set org.gtk.gtk4.Settings.FileChooser show-hidden true
#gsettings set org.gtk.Settings.FileChooser startup-mode recent
#gsettings set org.gtk.gtk4.Settings.FileChooser startup-mode recent
