#!/usr/bin/env bash
# set -e
set -u

# Check keys on the physical keyboard:
# sudo keyd -m

locale='[ids]
*

[main]
compose = layer(meta)
capslock = layer(nav)

[nav]
h = left
k = up
j = down
l = right
р = left
л = up
о = down
д = right\n'

conf="/etc/keyd/default.conf"

printf "\n$conf:\n\n"
printf "$locale" | sudo tee "$conf"

set -x

if command -v pacman &> /dev/null; then
  sudo pacman -S keyd
else
  set +x
  echo "Arch Linux only, so far"
  exit 1
fi

sudo systemctl enable --now keyd
