#!/usr/bin/env bash
# set -e
set -u

# Check keys on the physical keyboard:
# sudo keyd -m

locale='[ids]
*

[main]
compose = layer(meta)
capslock = layer(nav)
kpdot = compose

[nav]
h = left
k = up
j = down
l = right\n'

conf="/etc/keyd/default.conf"

printf "\n$conf:\n\n"
printf "$locale" | sudo tee "$conf"

set -x

# An attempt at installing keyd on Arch Linux.
if command -v pacman &> /dev/null; then
  sudo pacman -S keyd
fi

if [ "$(command -v keyd)" ]; then
  sudo systemctl enable --now keyd
else
  exit 1
fi
