#!/usr/bin/env bash
#
# Tweaking the KDE apps already installed in pure Gnome environment.
#

# Dolphin requires applications.menu configuration file:

apps_url="https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu"

menus_dir="$HOME/.config/menus"
apps_menu="$menus_dir/applications.menu"

# Download the config and rebuild the KDE cache.
dl_command() {
    curl -L $apps_url -o $apps_menu
    kbuildsycoca6 --noincremental
}

mkdir -p $menus_dir

if [[ -f "$apps_menu" ]]; then
    read -rp "File $apps_menu exists. Overwrite? (y/n): " answer && \
    if [[ "$answer" =~ ^[Yy] ]]; then
        $dl_command
    fi
    exit 0
fi

$dl_command
