#!/bin/bash
# Borrowed from https://github.com/officialrajdeepsingh/nerd-fonts-installer
#
font_name="Noto"

echo "Starting download $font_name nerd font"

if [ "$(command -v curl)" ]; then
    echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
    curl -OL "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
    echo "creating fonts folder: ${HOME}/.fonts"
    mkdir -p  "$HOME/.fonts"
    echo "unzip the $font_name.zip"
    unzip "$font_name.zip" -d "$HOME/.fonts/$font_name/"
    #fc-cache -fv
    echo "done!"

elif [ "$(command -v wget)" ]; then
    echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
    wget "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
    echo "creating fonts folder: ${HOME}/.fonts"
    mkdir -p  "$HOME/.fonts"
    echo "unzip the $font_name.zip"
    unzip "$font_name.zip" -d "$HOME/.fonts/$font_name/"
    #fc-cache -fv
    echo "done!"

else
    
    echo "We cannot find the curl and wget command. First, install the curl and wget command, one of them."

fi
