#!/usr/bin/env bash

echo "Creating fonts folder: ${HOME}/.fonts"
mkdir -p  "$HOME/.fonts"

nerd_name="Noto"
nerd_file="$nerd_name.zip"
nerd_url="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$nerd_file"

nerd_download_dir="$HOME/Downloads/Fonts/Nerd"
mkdir -p "$nerd_download_dir"

echo "Starting download $nerd_name nerd font"

cd "$nerd_download_dir"

if ! test -e "$nerd_file"; then
    if [ "$(command -v cnerd_url)" ]; then
        echo "$nerd_url"
        cnerd_url -OL "$nerd_url"
    elif [ "$(command -v wget)" ]; then
        echo "$nerd_url"
        wget "$nerd_url"
    else
        echo "Fatal error: no curl, no wget on the system"
        exit 1
    fi
fi

echo "unzip the $nerd_file"
unzip "$nerd_file" -d "$HOME/.fonts/$nerd_name/"

# A tiny addition: the Church Slavonic fonts.

nerd_name="fonts-churchslavonic"
nerd_file="$nerd_name.zip"
nerd_url="https://www.ponomar.net/files/$nerd_file"

nerd_download_dir="$HOME/Downloads/Fonts/Nerd"
mkdir -p "$nerd_download_dir"

echo "Starting download $nerd_name nerd font"

cd "$nerd_download_dir"

if ! test -e "$nerd_file"; then
    if [ "$(command -v cnerd_url)" ]; then
        echo "$nerd_url"
        cnerd_url -OL "$nerd_url"
    elif [ "$(command -v wget)" ]; then
        echo "$nerd_url"
        wget "$nerd_url"
    else
        echo "Fatal error: no curl, no wget on the system"
        exit 1
    fi
fi

echo "unzip the $nerd_file"
unzip "$nerd_file" -d "$HOME/.fonts/$nerd_name/"

fc-cache -fv
echo "Done!"
