#!/usr/bin/env bash

nerd_name="Noto"
nerd_file="$nerd_name.zip"
nerd_url="https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$nerd_file"

download_dir="$HOME/Downloads/Fonts/Nerd"
mkdir -p "$download_dir"

echo "Starting download $nerd_name nerd font"

cd "$download_dir"

if ! test -e "$nerd_file"; then
    if [ "$(command -v cnerd_url)" ]; then
        echo "$nerd_url"
        cnerd_url -OL "$nerd_url"
    elif [ "$(command -v wget)" ]; then
        echo "$nerd_url"
        wget "$nerd_url"
    else
        echo "We cannot find the curl and wget command. First, install the curl and wget command, one of them."
        exit 1
    fi
fi

echo "creating fonts folder: ${HOME}/.fonts"
mkdir -p  "$HOME/.fonts"
echo "unzip the $nerd_file"
unzip "$nerd_file" -d "$HOME/.fonts/$nerd_name/"
fc-cache -fv
echo "done!"
