#!/usr/bin/env bash
# set -e
set -u
set -x

local_path="$HOME/.local/bin"
path="/usr/bin"
sdkmgr="$path/sdkmanager"

if [ ! "$(command -v $sdkmgr)" ]; then
    set +x
    echo "Can't install Android SDK: no $sdkmgr on the system"
    exit 1
fi

sudo $sdkmgr --install "platform-tools"
sudo $sdkmgr --install "platforms;android-35"
sudo $sdkmgr --install "build-tools;35.0.1"
sudo $sdkmgr --install "cmdline-tools;latest"

sudo chown -R $USER:$USER /opt/android-sdk

yes |sudo $sdkmgr --licenses

sudo chown -R $USER:$USER /opt/android-sdk/licenses

yes |sdkmanager --licenses
