#!/usr/bin/env bash
# set -e
set -u
set -x

# The script can be run securely multiple times.

if [ ! "$(command -v zsh)" ]; then
  echo "Zsh package missing"
  exit 1
fi

rm -rf ~/.oh-my-zsh
rm -rf ~/.oh-my-zsh-cache
rm -rf ~/.antidote
rm -rf ~/.cache/antidote
rm -rf ~/.cache/p10k*
rm -rf ~/.local/share/sheldon

yes | cargo binstall sheldon
yes | cargo binstall zsh-patina

~/.local/share/chezmoi/fzf-install

set +x

# Set default login shell (may prompt for password)
chsh -s "$(which zsh)" || exit 1
echo "⮞ ⮞ ⮞ LOG OUT, THEN LOG IN AGAIN ⮜ ⮜ ⮜"
