#!/usr/bin/env bash
# set -e
set -u
set -x

# Miscellaneous applications.

# yay -S google-chrome
yay -S qutebrowser
yay -S geany geany-plugins
if [ $(uname -m) == 'x86_64' ]; then
    yay -S doublecmd-qt5
    yay -S foxitreader
    yay -S zoom
    yay -S yacreader
fi
