#!/usr/bin/env bash
# set -e
set -u
set -x

# Before running this script make sure that
# 1. ./all-prepare script has been run
# 2. Chezmoi has been set up according to README
#    Like $ chezmoi init https://github.com/Tyrn/dotfiles.git

# ./rwasm-install
./base-install
./extras-install
# ./flutter-install
./spell-install
./nvim-install
# ./doom-install
./qemu-install
# ./nix-init
./racket-install
./typst-install
chezmoi apply --force
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install  # Say no to Do you want to update your shell config...
gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#FFD700'
