#!/usr/bin/env bash
# set -e
set -u
set -x

# Build essentials, to be installed before trying all-install.

sudo dnf install -y @c-development
sudo dnf install -y fontconfig-devel freetype-devel libstdc++-static
sudo dnf install -y libstdc++-devel gettext-devel
sudo dnf install -y clang cmake meson gtest doxygen pipx micro

curl https://sh.rustup.rs -sSf | sh
rustup toolchain install nightly

# Ecosystem essentials.

../noto-nerd-install
./admin-add

echo "!!! REBOOT !!!"
sudo shutdown -r now
