#!/usr/bin/env bash
# set -e
set -u
set -x

# Before running this script make sure that
# 1. ./all-prepare script has been run
# 2. Chezmoi has been set up according to README
#    Like $ chezmoi init https://github.com/Tyrn/dotfiles.git

./base-install
# ./rwasm-install
./extras-install
# ./flutter-install
./spell-install
./nvim-install
# ./doom-install
./qemu-install
# ./nix-init
# ./racket-install
./typst-install
chezmoi apply --force
gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#FFD700'
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent 'true'
