#!/usr/bin/env bash
# set -e
set -u
set -x

rustup component add rust-analyzer
cargo install cargo-binstall
yes | cargo binstall cargo-update

sudo dnf install -y docker docker-compose docker-buildx
docker buildx install
sudo systemctl enable docker

sudo dnf install -y @kde-apps qbittorrent
sudo dnf install -y gparted fastfetch kdialog tig tmux atool tk zstd

yes | cargo binstall du-dust
yes | cargo binstall bottom

sudo dnf install -y ripgrep fd-find sd bat eza erdtree htop btop gdu
sudo dnf install -y procs tealdeer skim tokei difftastic alacritty alien
sudo dnf install -y zathura zathura-pdf-poppler yt-dlp fontforge taglib-devel

sudo dnf install -y AtomicParsley aria2 python3-pycryptodomex python3-websockets
sudo dnf install -y rpi-imager smartmontools gnome-browser-connector

#yay -S ttf-liberation
#yay -S ttf-dejavu

# CUPS drivers for SPL (Samsung Printer Language) printers.

sudo dnf install -y splix

# Python, forgettable.

pipx install poetry
pipx install uv
pipx install mkdocs-material --include-deps


sudo dnf install -y python3-lsp-server python3-lsp-black black
sudo dnf install -y python3-ipython ptpython3

sudo dnf install -y nodejs-bash-language-server
