#!/usr/bin/env bash
# set -e
set -u
set -x

# Build essentials, to be installed before everything,
# including Rust.

sudo pacman -S yay
yay -S fakeroot

yay -S base-devel
yay -S clang
yay -S doxygen
