#!/usr/bin/env bash
# set -e
set -u
set -x

# Build essentials, to be installed before everything.

sudo dnf install -y @c-development
sudo dnf install -y fontconfig-devel freetype-devel libstdc++-static
sudo dnf install -y libstdc++-devel

sudo dnf install -y clang cmake doxygen pipx
