#!/usr/bin/env bash
# set -e
set -u
set -x

# Miscellaneous applications.

sudo dnf install -y google-chrome-stable qutebrowser
sudo dnf install -y geany geany-plugins-addons geany-plugins-vimode

#yes | flatpak install flathub com.vscodium.codium  # flatpak run com.vscodium.codium
#yes | flatpak install cc.arduino.arduinoide
#yes | flatpak install flathub us.zoom.Zoom
#yes | flatpak install flathub org.x.Warpinator

yes | cargo binstall tex-fmt

sudo dnf install -y retext watchman pandoc opusfile qmmp mpv puddletag
sudo dnf install -y kdenlive vorbis-tools yacreader

# CRAN (R Studio)
#sudo dnf copr enable iucar/cran
#sudo dnf install R-CoprManager

# scrcpy - Something for Android
