#!/usr/bin/env bash
# set -e
set -u
set -x

# Miscellaneous applications.

sudo dnf config-manager setopt google-chrome.enabled=1

sudo dnf install -y google-chrome-stable qutebrowser
sudo dnf install -y geany geany-plugins-addons geany-plugins-vimode

sudo dnf install -y retext watchman pandoc opusfile qmmp mpv puddletag
sudo dnf install -y kdenlive vorbis-tools yacreader
sudo dnf install -y gnome-tweaks gnome-extensions-app

yes | cargo binstall tex-fmt

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#flatpak install flathub org.telegram.desktop
#flatpak install flathub org.torproject.torbrowser-launcher
#flatpak install flathub com.vscodium.codium  # flatpak run com.vscodium.codium
#flatpak install cc.arduino.arduinoide
#flatpak install flathub us.zoom.Zoom
#flatpak install flathub org.x.Warpinator

# CRAN (R Studio)
#sudo dnf copr enable iucar/cran
#sudo dnf install R-CoprManager

# scrcpy - Something for Android
