#!/usr/bin/env bash
# set -e
set -u
set -x

sudo usermod -aG dialout $USER  # Aka uucp in other systems.

sudo groupadd nix-users
sudo usermod -aG nix-users $USER

sudo groupadd docker
sudo usermod -aG docker $USER

sudo groupadd libvirt
sudo usermod -aG libvirt $USER

sudo groupadd kvm
sudo usermod -aG kvm $USER
