#!/usr/bin/env bash
# set -e
set -u
set -x

# MicroPython.

pipx install adafruit-ampy
pipx install rshell

# AstroNvim.

#yay -S neovim-remote  # (AUR only).
sudo dnf install -y tree-sitter
sudo dnf install -y python3-jedi python3-neovim
yes | cargo binstall neovide

sudo rm -rf ~/.cache/nvim ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim

git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
sudo rm -rf ~/.config/nvim/.git
sudo dnf install -y neovim

chezmoi apply --force
