#!/usr/bin/env bash
# set -e
set -u
set -x

# QEMU/KVM/Virtual Machine Manager.
# Necessary groups already set by groups-add.

sudo dnf install -y qemu virt-manager

sudo systemctl enable --now libvirtd
