#!/usr/bin/env bash
# set -e
set -u
set -x

# Racket.

sudo dnf install -y racket
yes | raco pkg install infix
yes | raco pkg install from-template
yes | raco pkg install fmt
yes | raco pkg install pie
yes | raco pkg install racket-langserver
