#!/usr/bin/env bash
# set -e
set -u
set -x

curl https://sh.rustup.rs -sSf | sh
rustup toolchain install nightly
rustup component add rust-analyzer
# rustup component add rust-src
yes | cargo install cargo-binstall
yes | cargo binstall cargo-update

# Updating cargo-binstall: cargo binstall cargo-binstall
