#!/usr/bin/env bash
# set -e
set -u
set -x

sudo dnf install rustup
rustup toolchain install nightly
rustup component add rust-analyzer
# rustup component add rust-src
cargo install cargo-binstall

# Updating cargo-binstall: cargo binstall cargo-binstall
