#!/usr/bin/env bash
# set -e
set -u
set -x

# Typst.

cargo binstall typst-cli
cargo binstall typstyle
# cargo install --git https://github.com/typst/typst --locked typst-cli
# yay -S typst
# yay -S tinymist
